
// string method ........>
// length .....>
// trimStart ......>
// trimEnd  ......>
// trim    ......>
// toUpperCase ......>
// toLowerCase  ......>
// toString   
// substring
// startsWith  ......>
// endsWith   ......>
// split 
// slice
// replace
// replaceAll
// repeat
// lastIndexOf
// indexOf
// includes

// concat

// charAt


// INTERVIEW QUESTION

// swap vale without using 3 variable
// factorial
// Array dsa question
// hoisting
// get ,post,patch,delete
// 2 question of database
// General question regarding yourself
// basics of html and css finish


// It is the basic characteristic of an object, generated by default and based on the structure of property name plus property value. For example all strings in JavaScript always have the property "length", which describes how many characters in it.

//////////////////////////////////////////////////////////////////////////

// // 1} length

// // pending

// let name = "hema v mane"
// let newstr = name.split(" ").join("")
// // console.log(newstr)

// // let arr = []

// // for(let i=0; i<name.length; i++){
// //     console.log(i)
// // }
// let arr =[]
// for(let i=0; i<newstr.length; i++){
//         // console.log(newstr[i].length)
//         arr.push(newstr[i].length)
// }

// let max = Math.max(...arr)
// // console.log(max)
// for(let i=0; i<newstr.length; i++){
//         //    console.log("k",newstr[i])
//     if(newstr[i].length===max){
//         console.log(newstr[i])
//     }
// }


// console.log("hii")
// let ar;
// console.log(typeof  ar)

// strings are used for holding data that represents  in text form
//   

// Charcter access
// charAt()
// console.log("first"[3])

// const a = "a";
// const b = "b";
// if (a < b) {
//   // true
 
//   console.log(`${a} is less than ${b}`);
// } else if (a > b) {
 
//   console.log(`${a} is greater than ${b}`);
// } else {
//   console.log(`${a} and ${b} are equal.`);
// }


// let k =" hema        ri        k    "
// console.log(k.trimStart())
// console.log("h    e           m   a".split(" ").join(""))
// console.log(k)

// it will return the new string which is whitespace removed
// and trim() will remove oboth side of string whitespace only
// trimEnd() remove only from end whitespaces
// trimStart() remove only from start whitespaces


// function str(name){

// let newstr = name[0].toUpperCase()

//////////////////////////////////////////////////////////////////////////////////////

// for(let i=1; i<name.length; i++){
// //    console.log(name[i],i)
//     if(name[i]==" "){
        
//     newstr += " "+name[i+1].toUpperCase()
//        i++
//     }
//     else{
//         newstr += name[i]
//     }
  
// }
// return newstr
// }
// console.log(str("i am good student"))


// TOSTRING
// let name = "hema mane"

// startsWith()/////////////////////////////////////
// this function defineds the  starting of string 
// let name = "hema"
// console.log(name.startsWith("m"))

// endsWith()////////////////////
// its is use to find end of string
// let name = "hema"
// console.log(name.endsWith(""))

// toString tostring()/////////
// let name = "vasanth"
// let num = 5
// console.log(num.toString())

















